# Generated by Django 5.2.17 on 2026-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_a87c6f_idx',
            old_name='orders_ord_user_id_6e4c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_ord_status_7d8d9a_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_f0ce29_idx',
            old_name='orders_ord_created_9c0e8f_idx',
        ),
    ]
