# Generated by Django 5.2.17 on 2026-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_9edb3d_idx',
            old_name='products_pr_categor_0d3c4c_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_ca4d9a_idx',
            old_name='products_pr_is_acti_1c9e4b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_price_9b1a5f_idx',
            old_name='products_pr_price_4f9a3b_idx',
        ),
    ]
